name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write          # allow the action (PAT) to push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build with Snowpack
        # assumes "snowpack" script outputs to ./docs
        run: npm run snowpack

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          github_token: ${{ secrets.GH_PAGES_TOKEN }}   # <-- your PAT secret
